POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "testNamw{{$random.integer(3)}}",
  "email": "{{$random.alphabetic(5)}}@gmail.com",
  "city": "Moscow",
  "password": "123456",
  "role": "customer",
  "avatar": "{{$exampleServer}}/avatar/{{$random.alphanumeric(4)}}.jpg",
  "birthDay": "{{$isoTimestamp}}",
  "aboutMe": "{{$random.alphabetic(3)}} {{$random.alphabetic(5)}} {{$random.alphabetic(8)}}",
  "specialization": "{{$random.alphabetic(10)}}"
}

###
