POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "testNamw{{$random.integer(3)}}",
  "email": "{{$random.alphabetic(5)}}@gmail.com",
  "city": "Moscow",
  "password": "123456",
  "role": "customer",
  "avatar": "{{$exampleServer}}/avatar/{{$random.alphanumeric(4)}}.jpg",
  "birthDay": "{{$isoTimestamp}}",
  "aboutMe": "{{$random.alphabetic(3)}} {{$random.alphabetic(5)}} {{$random.alphabetic(8)}}",
  "specialization": "{{$random.alphabetic(10)}}"
}

###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "qQONY@gmail.com",
  "password": "123456"
}

###

GET http://localhost:3001/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGY5ZjlmMWIzZDlmNzRkNDM5ZmRlOWUiLCJlbWFpbCI6InFRT05ZQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsIm5hbWUiOiJ0ZXN0TmFtdzAiLCJpYXQiOjE2OTQxNjg1NTEsImV4cCI6MTY5NDI1NDk1MX0.FpEQlxv7tV2_sS9mF7vZb1ens5IAQjHBsBUpqepbCco
